jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "GROUP:Overall/Read:authenticated"
  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: github-jenkins
              username: ${JENKINS_ADMIN_ID}
              description: "SSH passphrase with private key file"
              privateKeySource:
                directEntry:
                  privateKey: "${SSH_PRIVATE_KEY}"
          - string:
              scope: GLOBAL
              id: github-jenkins-access-token
              description: "GitHub access token for Jenkins"
              secret: "${GITHUB_ACCESS_TOKEN}"
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub
              description: dockerhub login access for Jenkins
              username: "${DOCKER_USERNAME}"
              password: "${DOCKER_PASSWORD"
              usernameSecret: true
jobs:
  - script: >
      pipelineJob('arr-media-server-dev') {
        definition {
          cpsScm {
            lightweight(true)
            scm {
              git {
                remote {
                  url("https://github.com/DarkMurky/arr-media-server.git")
                  credentials("github-jenkins")
                }
                branch("*/dev")
              }
            }
            triggers {
              githubPush()
            }
            scriptPath("Jenkinsfile")
          }
        }
        parameters {
          stringParam('environment', 'dev', 'environment')
        }
      }
  - script: >
      pipelineJob('arr-media-server-prod') {
        definition {
          cpsScm {
            lightweight(true)
            scm {
              git {
                remote {
                  url("https://github.com/DarkMurky/arr-media-server.git")
                  credentials("github-jenkins")
                }
                branch("*/main")
              }
            }
            triggers {
              githubPush()
            }
            scriptPath("Jenkinsfile")
          }
        }
        parameters {
          stringParam('environment', 'prod', 'environment')
        }
      }

security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy
